pool 2.gentoo.pool.ntp.org iburst maxsources 4
server time.windows.com iburst
server time.apple.com iburst
server ntp.ntsc.ac.cn iburst

driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
rtconutc
