[boot]
# Keep WSL simple. Do not run full OpenRC by default unless you really need services.
systemd = false
# command = /sbin/openrc default

[automount]
enabled = true
root = /mnt/
options = "metadata,umask=22,fmask=11"
mountFsTab = false

[interop]
enabled = true
appendWindowsPath = false

[user]
default = kl

[network]
generateHosts = true
generateResolvConf = true
