# created by eselect-repo

[gentoo-zh]
location = /var/db/repos/gentoo-zh
sync-type = git
sync-uri = https://github.com/microcai/gentoo-zh.git


[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[xlibre]
location = /var/db/repos/xlibre
priority = 100
sync-type = git
sync-uri = https://github.com/X11Libre/ports-gentoo.git
